### ISSUE TITLE
I  have followed README,but there is no folder "swbd".  So there may be several files missing

### ISSUE THREAD

**Issue by lizhzh8** [ishalyminov/multitask_disfluency_detection#14]
python make_deep_disfluency_dataset.py swbd disfluency

![image](https://user-images.githubusercontent.com/30767119/82198760-5bbf5580-992f-11ea-8140-fca6a120b82f.png)

**Comment by ishalyminov** [comment]
Hmm, are you sure you're using the code from the master branch without any modifications?
This script only takes the required positional args: https://github.com/ishalyminov/multitask_disfluency_detection/blob/2148a04a63e592e277a6fd4131ec9b8287fb619a/make_deep_disfluency_dataset.py#L62

**Comment by ishalyminov** [comment]
To make it clear, when you invoke the script like this:

`python make_deep_disfluency_dataset.py swbd disfluency`

-- the script creates the `swbd` folder itself and puts there the processed dataset in the `disfluency` format. So no extra files or folders are required for it to run - apart from the `deep_disfluency` stuff which we covered in the previous issue.

The only problem I see with the output you have pasted is that `--result_folder RESULT_FOLDER` and `--format FORMAT` are both optional arguments whereas the original script takes 2 positional arguments as you can see at the above link. So please make sure you're using the version of the script exactly as at the link above.

**Comment by lizhzh8** [comment]
Actually when I run `git submodule update --init`，there is some error.

![image](https://user-images.githubusercontent.com/30767119/82277810-61627d00-99bb-11ea-96b9-8bd279f11b9d.png)

**Comment by ishalyminov** [comment]
That looks weird, I experienced that as well recently. Mind creating another issue for that?

**Comment by lizhzh8** [comment]
OK
