### ISSUE TITLE
when I use  " git submodule update --init ", I get  some error as followed.

### ISSUE THREAD

**Issue by lizhzh8** [ishalyminov/multitask_disfluency_detection#15]
![image](https://user-images.githubusercontent.com/30767119/82278130-0b420980-99bc-11ea-81c4-1f186e83cf67.png)

So I have to use 
![image](https://user-images.githubusercontent.com/30767119/82278231-50fed200-99bc-11ea-936a-0b3a88ee862c.png) to download the submodule. 

Is there any other way to solve the problems? Thank you .

**Comment by lizhzh8** [comment]
Fortunately, I ran through the whole process.

![image](https://user-images.githubusercontent.com/30767119/82279513-5578ba00-99bf-11ea-95d8-84192bbf028c.png)

**Comment by ishalyminov** [comment]
Glad to see it worked for you!
Regarding the submodule problem, I experienced it recently as well, but not anymore - looks like there was some problem on the GitHub side.
Please re-open this issue if you keep experiencing this.
