### ISSUE TITLE
hi,  I read your <Multi-Task Learning for Domain-General Spoken Disfluency Detection in Dialogue Systems>,and I want to repeat this code. But where is the  data? 

### ISSUE THREAD

**Issue by lizhzh8** [ishalyminov/multitask_disfluency_detection#5]
Switchboard Dialogue Acts(SWDA) corpus is not found.
Can you tell me? Thanks

![image](https://user-images.githubusercontent.com/30767119/81765317-100f4500-9506-11ea-9737-33be0cb527f0.png)

**Comment by ishalyminov** [comment]
Hi there,

I believe you need to run [this script](https://github.com/ishalyminov/multitask_disfluency_detection/blob/master/make_deep_disfluency_dataset.py) - just please make sure the `deep_disfluency` submodule is properly initialized beforehand.

Also please feel free to post here any updates on your progress and possible further questions - that will help me collect a comprehensive update to the README.md:)

**Comment by lizhzh8** [comment]
> Hi there,
> 
> I believe you need to run [this script](https://github.com/ishalyminov/multitask_disfluency_detection/blob/master/make_deep_disfluency_dataset.py) - just please make sure the `deep_disfluency` submodule is properly initialized beforehand.
> 
> Also please feel free to post here any updates on your progress and possible further questions - that will help me collect a comprehensive update to the README.md:)

Firstly,thank you!
And , `make_deep_disfluency_dataset.py` script alse need  train/heldout/test data.

![image](https://user-images.githubusercontent.com/30767119/81767745-c295d680-950b-11ea-8fc9-9081ec989a19.png)

**Comment by lizhzh8** [comment]
And by the way, the 'bAbI+ disfluency study data generation' part in README.md is no problem, I have got the resulting datasets.

**Comment by ishalyminov** [comment]
> > Hi there,
> > I believe you need to run [this script](https://github.com/ishalyminov/multitask_disfluency_detection/blob/master/make_deep_disfluency_dataset.py) - just please make sure the `deep_disfluency` submodule is properly initialized beforehand.
> > Also please feel free to post here any updates on your progress and possible further questions - that will help me collect a comprehensive update to the README.md:)
> 
> Firstly,thank you!
> And , `make_deep_disfluency_dataset.py` script alse need train/heldout/test data.
> 
> ![image](https://user-images.githubusercontent.com/30767119/81767745-c295d680-950b-11ea-8fc9-9081ec989a19.png)

No problem! Yes, [here they are](https://github.com/clp-research/deep_disfluency/tree/91bcbf31a39b71e06c74439c1acf75f656e555e0/deep_disfluency/data/disfluency_detection/switchboard), part of the `deep_disfluency` repo - that's why you may want to initialize the submodule first. Just run:
```
git submodule update --init
```

**Comment by lizhzh8** [comment]
the environment need bleach==1.5.0 ,but  bleach==3.0.0 in requirement_cpu.txt . 
![image](https://user-images.githubusercontent.com/30767119/81777133-c7b25000-9522-11ea-8512-4f1fefe6b41b.png)

**Comment by lizhzh8** [comment]
Maybe add python-crfsuite==0.9.7 in  requirement_cpu.txt 。

**Comment by lizhzh8** [comment]
Now,I get trainset.json/devset.json/testset.json .
But when I run train.py,I get an error as follow.   the problem may be about Tensor form. why occurs the problem?


`ssh://root@172.16.176.60:22/root/anaconda3/envs/disfluency_detection_py2/bin/python -u /home/lizz/multitask_disfluency_detection-master/train.py result_folder models
/root/anaconda3/envs/disfluency_detection_py2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2020-05-13 15:03:58.396908: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/lizz/multitask_disfluency_detection-master/train.py", line 111, in <module>
    main(args.dataset_folder, args.model_folder, args.resume, config)
  File "/home/lizz/multitask_disfluency_detection-master/train.py", line 103, in main
    task_weights=config['task_weights'])
  File "/home/lizz/multitask_disfluency_detection-master/dialogue_denoiser_lstm.py", line 76, in train
    task_weights=task_weights)
  File "/home/lizz/multitask_disfluency_detection-master/training_utils.py", line 116, in get_loss_function
    v_initial = graph.get_tensor_by_name(v.name.partition(':')[0] + '_initial:' + v.name.partition(':')[1])
  File "/root/anaconda3/envs/disfluency_detection_py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3635, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/root/anaconda3/envs/disfluency_detection_py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3459, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/root/anaconda3/envs/disfluency_detection_py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3495, in _as_graph_element_locked
    "form \"<op_name>:<output_index>\"." % repr(name))
ValueError: The name 'model/emb_initial::' looks a like a Tensor name, but is not a valid one. Tensor names must be of the form "<op_name>:<output_index>".`

**Comment by ishalyminov** [comment]
That is something I haven't seen before. Could you please paste here 1) your python version, 2) the output of `pip freeze`, and 3) the commands you ran to get to that point?

**Comment by lizhzh8** [comment]
> That is something I haven't seen before. Could you please paste here 1) your python version, 2) the output of `pip freeze`, and 3) the commands you ran to get to that point?

1) 
![image](https://user-images.githubusercontent.com/30767119/81882170-9db16a00-95c4-11ea-99e3-f8c0af2a6ecd.png)

2)
![image](https://user-images.githubusercontent.com/30767119/81882242-d0f3f900-95c4-11ea-8118-8a86439d6f72.png)
![image](https://user-images.githubusercontent.com/30767119/81882281-e701b980-95c4-11ea-9188-ecd14244241d.png)
![image](https://user-images.githubusercontent.com/30767119/81882302-f84ac600-95c4-11ea-9308-ce7ad7afbc20.png)

3) the command I ran to get that point is "python train.py result_folder/ models/". And the dataset_folder in "parser.add_argument('dataset_folder')" is "result_folder/" directory,and the model_folder in parser.add_argument('model_folder') is "models" directory.
![image](https://user-images.githubusercontent.com/30767119/81882986-adca4900-95c6-11ea-95e0-baf5d8be95a7.png)

**Comment by lizhzh8** [comment]
And  I actually use the conda command to create a new and independency python environment. Then `pip install -r requirement_cpu.txt`. So I don't know  why the problem happened.
![image](https://user-images.githubusercontent.com/30767119/81884065-727d4980-95c9-11ea-8ad2-2b5fbc1260d2.png)

**Comment by ishalyminov** [comment]
Thanks for the exhaustive info! Please give me a few days to look into this

**Comment by lizhzh8** [comment]
> Thanks for the exhaustive info! Please give me a few days to look into this

Thank you.I'm also trying to fix this program .

**Comment by ishalyminov** [comment]
Fixed now, and added python-crfsuite to requirements as you suggested. Please re-open this if you keep having this problem. For other questions, please create new issues for the sake of clarity.
